version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: web
    container_name: web
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      - mysql
    volumes:
      - ./:/app
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_SCHEMA
    ports:
      - "$DB_PORT:$DB_PORT"
volumes:
  dbdata:
